tickers = ["YPF","BMA","GGAL","IRS","TEO","SUPV","BBAR","TGS","PAM","LOMA","CEPU","CRESY","EDN",
        "AAL", "AAP", "AAPL", "ABBV", "ABEV", "ABNB", "ABT",
        "ACN", "ADBE", "AGRO", "ADI", "ADP", "AEM", "AMAT",
        "AMD", "AMGN", "AMX", "AMZN", "ANF", "ARCO", "ARM", "ASR",
        "AVGO", "AVY", "AZN","ASML","AI","TEAM","CLS","CEG","DECK","RGTI",
        "B", "BA", "BABA","NOW","VST","VRTX","PATH","PDD","XPEV",
         "BAK", "BB", "BHP","BRK-B",
        "BIDU", "BIIB", "BIOX", "BITF", "BKNG", "BKR", "BMY",
        "BP", "BRFS", "CAAP", "CAH",
         "CAR", "CAT", "CCL", "CDE", "CL", "COIN", "COST", "CRM",
         "CSCO", "CSNA3.SA", "CVS", "CVX", "CX", "DAL", "DD",
        "DE", "DEO", "DHR", "DIS", "DOCU", "DOW",
        "E", "EA", "EBAY", "EBR","EFX", "EQNR", "ERIC",
        "ERJ", "ETSY", "F", "FCX", "FDX",
        "FMX", "FSLR", "GE", "GFI", "GGB", "GILD",
        "GLOB", "GLW", "GM", "GOOGL", "GRMN",
        "GSK", "GT", "HAL", "HAPV3.SA", "HD", "HL", "HMC", "HMY",
        "HOG", "HON", "HPQ", "HSY", "HUT", "HWM",
         "IBM", "INFY", "INTC", "IP",
        "ISRG","JBSS3.SA",
        "JD", "JMIA", "JNJ","JOYY", "KEP", "KGC",
        "KMB", "KO", "KOD", "LAC", "LAR", "LLY",
        "LMT", "LND", "LRCX", "LREN3.SA", "LVS",  "MA", "MCD",
         "MDLZ", "MDT", "MELI", "META", "MGLU3.SA", "MMC", "MMM",
        "MO", "MOS", "MRK", "MRNA", "MRVL", "MSFT", "MSI", "MSTR",
        "MU", "MUX", "NEM", "NFLX", "NG", "NGG", "NIO",
        "NKE", "NTCO", "NTES", "NUE", "NVDA", "NVS",
        "NXE", "ORCL", "ORLY", "OXY", "PAAS", "PAC", "PAGS", "PANW", "PBI",
        "PBR", "PCAR", "PEP", "PFE", "PG",
        "PHG", "PINS", "PLTR", "PM", "PRIO3.SA", "PSX", "PYPL", "QCOM",
         "RACE", "RBLX", "RENT3.SA", "RIO", "RIOT", "ROKU", "ROST", "RTX",
         "SAP", "SATL", "SBS", "SBUX", "SCCO", "SDA", "SE",
        "SHEL", "SHOP", "SID", "SLB", "SNA", "SNAP", "SNOW", "SONY", "SPCE",
        "SPGI", "SPOT", "STLA", "STNE", "SYY", "T",
        "TCOM", "TEN", "TGT", "TIMB", "TM",
        "TMO", "TMUS", "TRIP", "TSLA", "TSM", "TTE", "TV", "TWLO",
        "TXN", "UAL", "UBER", "UGP", "UL", "UNH",
         "UNP", "URBN", "V", "VALE",
          "VIST", "VIV", "VOD", "VRSN", "VZ", "WBA", "WB", "WEGE3.SA", "WMT", "X", "XOM", "XP", "XRX",
        "XYZ", "YELP", "ZM", "ADS","AEG","AXP","AIG","BBD","BBAS3.SA","BSBR","SAN","BAC","BCS","BAS","BAYN",
        "BBV","SCHW","C","ELP","CS","BSN","DTEA","EOAN","AKO-B","FNMA", "FMCC","GPRK","HDB","HHPD",
        "HSBC","IBN","ING","IFF","JPM","ITUB","JCI","KB","LYG","MBG","MUFG","NEC1.HM","NSAN",
        "NOKA","NMR","PSO","PKS","SMSN","SWKS","TTM","RCTB4.BA","TIIAY","TEFO","TX","BK","GS","TRVV",
        "TJX", "USB", "UPST","WBO","WFC","AUY","YZCAY"
    ]